name: Daily Zodiac Fortune Generation

on:
  schedule:
    - cron: '0 15 * * *'  # UTC 15:00 (KST 00:00)
  workflow_dispatch:  # Allow manual execution

jobs:
  create-fortune:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      TZ: 'Asia/Seoul'  # Set timezone to Korea Standard Time (KST)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install Requirements (if needed)
      run: |
        # Optional step if there are specific Python dependencies
        pip install -r requirements.txt || echo "No dependencies to install"

    - name: Run Fortune Generator Script
      run: python generate_fortune.py

    - name: Configure Git for Push
      run: |
        git config --global user.email "shuaigejp80@gmail.com"
        git config --global user.name "hellomatia"

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "✨ update horoscope for $(date +'%Y-%m-%d')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
