name: Manual Fortune Generation

on:
  workflow_dispatch:  # This enables manual triggering

jobs:
  create-fortune:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Save Python Script
      run: |
        cat > generate_fortune.py << 'EOL'
        # Here paste the entire content of the Python script above
        # From "import random" to the last line
        EOL

    - name: Generate Fortune
      run: python generate_fortune.py

    - name: Push changes
      run: |
        git config --global user.email "shuaigejp80@gmail.com"
        git config --global user.name "hellomatia"
        git add .
        git commit -m "✨ ${today} horoscope update" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

